#!/usr/bin/env bash
# World wide web

func () {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomain="www lb-01 web-01 web-02"
    fi

    for sd in $subdomain; do
        dig "$sd.$domain" | awk -v sd="$sd" '/ANSWER SECTION:/ {getline; print "The subdomain " sd " is a " $4 " record and points to " $5}'
    done
}

func "$1" "$2"
