#!/bin/bash
echo $(( $(echo $WATER | tr '[:lower:]' '[:upper:]' | tr 'A-Z' '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ' ) + $(echo $STIR | tr '[:lower:]' '[:upper:]' | tr 'A-Z' '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ' ) )) | tr '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ' 'bestchol0123456789'
