#!/usr/bin/env bash
# Configures HAProxy so that it sends traffic to web-01 and web-02
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get update
apt-get install haproxy=2.8.\* -y

echo "backend myservers
    balance roundrobin
    server 373839-web-01 54.164.144.136:80 check
    server 373839-web-02 18.210.33.80:80 check
frontend http
    bind *:80
    mode http
    default_backend myservers
" >>/etc/haproxy/haproxy.cfg
systemctl restart haproxy
