#!/usr/bin/env bash
# Prints numbers from 1 to 100.
#+ FizzBuzz when the number is a multiple of 3 and 5
#+ Fizz when num is a multiple of 3
#+ Buzz when num is a multiple of 5

for i in {1..100}
do
	fb=$((($i % 3) + ($i % 5)))
	f=$(($i % 3))
	b=$(($i % 5))
	if [ $fb = 0 ]
	then
		echo "FizzBuzz"
	elif [ $f -eq 0 ]
	then
		echo "Fizz"
	elif [ $b -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
