#!/usr/bin/env bash
# Tells a story about etc/passwd

while IFS=: read -r usr pass id gId uId hD sH
do
	echo "The user $usr is part of the $gId gang, lives in $hD and rides $sH. $id's place is protected by the passcode $pass, more info about the user here: $uId"
done< /etc/passwd
