#!/usr/bin/env bash
# Prints bad luck on the 4th, good luck on the 8th, and Best School otherwise

i=1
while [ $i -lt 11 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i + 1 ))
done
