#!/usr/bin/env bash
# Prints numbers 1 to 20, in 4th itr prints 4 and bad luck from china
#+ in 9th itr prints 9 and bad luck from japan, and 17 bad luck from italy

i=1
while [ $i -lt 21 ]
do
	echo "$i"
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	i=$((i + 1 ))
done
