#!/usr/bin/env bash
# Gives Information about the school file

if [ -f "school" ]
then
	echo "school file exists"
	is_empty=$(wc school | cut -d ' ' -f 1)
	if [ "$is_empty" -eq 0 ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	echo "school is a regular file"

elif [ -d "school" ]
then
	echo "school file exists"
	echo "school file is not empty"

else
	echo "school file does not exist"
fi
